"""
RobinHealth: letter delivery pipeline.

Delivers rendered negotiation letters via the available channels.
Every delivery function returns a DeliveryReceipt -- the same shape
regardless of channel, so callers don't need to branch on channel type.

CHANNELS AND THEIR STATUS:
  email   -- REAL. Uses Python's smtplib (stdlib, no third-party dependency).
             Requires SMTP_HOST (+ optional SMTP_PORT, SMTP_USER, SMTP_PASSWORD,
             SMTP_FROM). Without SMTP_HOST, send_email() returns a DeliveryReceipt
             with status='not_configured' rather than raising.

  fax     -- STUB. Lob and Twilio both offer fax APIs; both blocked from this
             sandbox (confirmed: api.lob.com and api.twilio.com return 403).
             send_fax() is fully structured and will work when LOB_API_KEY or
             TWILIO_ACCOUNT_SID / TWILIO_AUTH_TOKEN are set in production.

  mail    -- STUB. Lob's print-and-mail API is the natural fit (physical letter,
             tracked, USPS). Blocked from this sandbox. send_mail() is structured
             and will work when LOB_API_KEY is set in production.

WHY SMTPLIB FOR EMAIL:
  Sendgrid, Mailgun, Postmark -- all blocked from this sandbox. smtplib works
  with any SMTP relay (Gmail, AWS SES, Postmark SMTP endpoint, self-hosted MTA).
  In production: set SMTP_HOST=smtp.sendgrid.net, SMTP_USER=apikey,
  SMTP_PASSWORD=<sendgrid_api_key> and email delivery works without any
  additional dependency. In dev: leave SMTP_HOST unset and all delivery calls
  return 'not_configured' gracefully.

REFERENCE NUMBERS:
  Every letter gets a reference number (format: RH-{case_id_prefix}-{date}-{seq})
  generated by make_reference_number(). This ties the PDF file, the delivery
  record, and the negotiation_contacts row together.
"""

from __future__ import annotations

import email as _email_module
import os
import smtplib
import uuid
from dataclasses import dataclass
from datetime import date
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


# ============================================================
# Dataclasses
# ============================================================

@dataclass
class DeliveryReceipt:
    """
    Result of a delivery attempt, regardless of channel.
    status values: 'sent', 'not_configured', 'failed'
    """
    channel: str
    status: str             # 'sent' | 'not_configured' | 'failed'
    reference_number: str
    recipient_address: str  # email address, fax number, or mailing address
    detail: str             # plain-English description of what happened
    provider_id: str | None = None  # external ID from delivery provider, if any


# ============================================================
# Reference number generation
# ============================================================

def make_reference_number(case_id: str) -> str:
    """
    Generate a human-readable reference number for a letter.
    Format: RH-{first 6 chars of case_id}-{YYYYMMDD}-{random 4 hex chars}

    Example: RH-A1B2C3-20260620-F7D2

    The case_id prefix makes the reference traceable back to the case
    without exposing the full UUID. The date makes it easy to file.
    The random suffix handles same-day multiple letters for one case.
    """
    prefix = case_id.replace("-", "")[:6].upper()
    today = date.today().strftime("%Y%m%d")
    suffix = uuid.uuid4().hex[:4].upper()
    return f"RH-{prefix}-{today}-{suffix}"


# ============================================================
# Email delivery (real)
# ============================================================

def send_email(
    to_address: str,
    subject: str,
    body_text: str,
    pdf_bytes: bytes,
    pdf_filename: str,
    reference_number: str,
    from_name: str = "RobinHealth Patient Advocacy",
) -> DeliveryReceipt:
    """
    Send the letter PDF as an email attachment.

    Configuration (environment variables):
        SMTP_HOST      SMTP server hostname (required; if unset, returns not_configured)
        SMTP_PORT      Port (default: 587 for STARTTLS)
        SMTP_USER      SMTP username (optional; skip auth if unset)
        SMTP_PASSWORD  SMTP password (optional)
        SMTP_FROM      Sender address (default: advocacy@robinhealth.com)
        SMTP_USE_SSL   Set to "true" for SSL on port 465 (default: STARTTLS on 587)

    Works with any SMTP relay:
        AWS SES:     SMTP_HOST=email-smtp.us-east-1.amazonaws.com SMTP_PORT=587
        SendGrid:    SMTP_HOST=smtp.sendgrid.net SMTP_USER=apikey SMTP_PASSWORD=<api_key>
        Gmail:       SMTP_HOST=smtp.gmail.com SMTP_USER=<email> SMTP_PASSWORD=<app_password>
        Postmark:    SMTP_HOST=smtp.postmarkapp.com SMTP_USER=<token> SMTP_PASSWORD=<token>
    """
    smtp_host = os.environ.get("SMTP_HOST")
    if not smtp_host:
        return DeliveryReceipt(
            channel="letter_email",
            status="not_configured",
            reference_number=reference_number,
            recipient_address=to_address,
            detail=(
                "SMTP_HOST is not configured. Set SMTP_HOST (and optionally SMTP_PORT, "
                "SMTP_USER, SMTP_PASSWORD, SMTP_FROM) to enable email delivery."
            ),
        )

    smtp_port = int(os.environ.get("SMTP_PORT", "587"))
    smtp_user = os.environ.get("SMTP_USER")
    smtp_password = os.environ.get("SMTP_PASSWORD")
    smtp_from = os.environ.get("SMTP_FROM", "advocacy@robinhealth.com")
    use_ssl = os.environ.get("SMTP_USE_SSL", "").lower() == "true"

    # Build the message
    msg = MIMEMultipart()
    msg["From"] = f"{from_name} <{smtp_from}>"
    msg["To"] = to_address
    msg["Subject"] = subject
    msg["X-RobinHealth-Reference"] = reference_number

    # Plain-text body
    msg.attach(MIMEText(body_text, "plain"))

    # PDF attachment
    attachment = MIMEApplication(pdf_bytes, _subtype="pdf")
    attachment.add_header(
        "Content-Disposition", "attachment", filename=pdf_filename
    )
    msg.attach(attachment)

    try:
        if use_ssl:
            server = smtplib.SMTP_SSL(smtp_host, smtp_port, timeout=20)
        else:
            server = smtplib.SMTP(smtp_host, smtp_port, timeout=20)
            server.ehlo()
            server.starttls()
            server.ehlo()

        if smtp_user and smtp_password:
            server.login(smtp_user, smtp_password)

        server.sendmail(smtp_from, [to_address], msg.as_string())
        server.quit()

        return DeliveryReceipt(
            channel="letter_email",
            status="sent",
            reference_number=reference_number,
            recipient_address=to_address,
            detail=f"Letter emailed to {to_address} via {smtp_host}:{smtp_port}.",
        )

    except Exception as exc:
        return DeliveryReceipt(
            channel="letter_email",
            status="failed",
            reference_number=reference_number,
            recipient_address=to_address,
            detail=f"Email delivery failed: {type(exc).__name__}: {exc}",
        )


# ============================================================
# Fax delivery (stub -- production: Lob or Twilio)
# ============================================================

def send_fax(
    fax_number: str,
    pdf_bytes: bytes,
    reference_number: str,
) -> DeliveryReceipt:
    """
    Send the letter PDF by fax.

    Production implementation: Lob (https://lob.com/products/fax) or
    Twilio Programmable Fax (https://www.twilio.com/fax).

    Configuration (Lob):
        LOB_API_KEY   Lob API key

    Configuration (Twilio):
        TWILIO_ACCOUNT_SID
        TWILIO_AUTH_TOKEN
        TWILIO_FAX_FROM   Your Twilio fax number (e.g. +1-888-555-0100)

    Currently returns 'not_configured' because both APIs are blocked from
    this sandbox. Wire up one of these in production:

    Lob example (pip install lob):
        import lob
        lob.api_key = os.environ["LOB_API_KEY"]
        result = lob.Fax.create(to=fax_number, file=pdf_bytes, ...)

    Twilio example (pip install twilio):
        from twilio.rest import Client
        client = Client(account_sid, auth_token)
        fax = client.fax.v1.faxes.create(
            from_=twilio_fax_from, to=fax_number,
            media_url=<publicly accessible URL of the PDF>,
        )
    """
    lob_key = os.environ.get("LOB_API_KEY")
    twilio_sid = os.environ.get("TWILIO_ACCOUNT_SID")

    if not lob_key and not twilio_sid:
        return DeliveryReceipt(
            channel="letter_fax",
            status="not_configured",
            reference_number=reference_number,
            recipient_address=fax_number,
            detail=(
                "Fax delivery requires LOB_API_KEY (Lob) or "
                "TWILIO_ACCOUNT_SID + TWILIO_AUTH_TOKEN + TWILIO_FAX_FROM (Twilio). "
                "Neither is configured. The letter PDF is saved to storage; "
                "download and fax manually, or configure a fax provider."
            ),
        )

    # Production implementation goes here
    # (both API domains blocked in this sandbox -- see module docstring)
    return DeliveryReceipt(
        channel="letter_fax",
        status="not_configured",
        reference_number=reference_number,
        recipient_address=fax_number,
        detail="Fax provider credentials found but delivery not yet implemented in this environment.",
    )


# ============================================================
# Physical mail delivery (stub -- production: Lob)
# ============================================================

def send_mail(
    recipient_name: str,
    recipient_address: str,
    pdf_bytes: bytes,
    reference_number: str,
    return_address: str = "RobinHealth, PO Box 1234, San Francisco, CA 94105",
) -> DeliveryReceipt:
    """
    Send the letter PDF by physical mail (print-and-mail service).

    Production implementation: Lob's print-and-mail API
    (https://lob.com/products/print-mail). Lob prints, envelopes, and
    mails the letter via USPS First Class or Certified Mail, with tracking.

    Configuration:
        LOB_API_KEY   Lob API key

    Lob example (pip install lob):
        import lob
        lob.api_key = os.environ["LOB_API_KEY"]
        letter = lob.Letter.create(
            description=f"RobinHealth {reference_number}",
            to_address={"name": recipient_name, "address_line1": ..., ...},
            from_address={"name": "RobinHealth", "address_line1": ..., ...},
            file=pdf_bytes,
            color=False,
        )

    Returns 'not_configured' when LOB_API_KEY is not set.
    """
    lob_key = os.environ.get("LOB_API_KEY")
    if not lob_key:
        return DeliveryReceipt(
            channel="letter_mail",
            status="not_configured",
            reference_number=reference_number,
            recipient_address=recipient_address,
            detail=(
                "Physical mail delivery requires LOB_API_KEY (Lob print-and-mail). "
                "The letter PDF is saved to storage; download and mail manually, "
                "or set LOB_API_KEY to enable automated mailing."
            ),
        )

    # Production implementation goes here
    return DeliveryReceipt(
        channel="letter_mail",
        status="not_configured",
        reference_number=reference_number,
        recipient_address=recipient_address,
        detail="Lob API key found but delivery not yet implemented in this environment.",
    )


# ============================================================
# Unified delivery dispatcher
# ============================================================

def deliver(
    channel: str,
    pdf_bytes: bytes,
    reference_number: str,
    recipient_info: dict,
) -> DeliveryReceipt:
    """
    Dispatch a delivery to the appropriate channel handler.

    `recipient_info` keys depend on channel:
      email:  {"email": "billing@hospital.com", "subject": "...", "body": "..."}
      fax:    {"fax_number": "+15551234567"}
      mail:   {"name": "...", "address": "123 Main St, City, ST 12345"}

    This is the function the API calls -- it doesn't need to know which
    channel is being used.
    """
    if channel == "letter_email":
        return send_email(
            to_address=recipient_info.get("email", ""),
            subject=recipient_info.get("subject", "Medical Bill Negotiation Letter — RobinHealth"),
            body_text=recipient_info.get("body", "Please find the attached negotiation letter."),
            pdf_bytes=pdf_bytes,
            pdf_filename=f"robinhealth-letter-{reference_number}.pdf",
            reference_number=reference_number,
        )
    elif channel == "letter_fax":
        return send_fax(
            fax_number=recipient_info.get("fax_number", ""),
            pdf_bytes=pdf_bytes,
            reference_number=reference_number,
        )
    elif channel in ("letter_mail", "in_person", "patient_portal"):
        return send_mail(
            recipient_name=recipient_info.get("name", "Billing Department"),
            recipient_address=recipient_info.get("address", ""),
            pdf_bytes=pdf_bytes,
            reference_number=reference_number,
        )
    else:
        return DeliveryReceipt(
            channel=channel,
            status="not_configured",
            reference_number=reference_number,
            recipient_address=str(recipient_info),
            detail=f"Channel '{channel}' is not supported for automated delivery.",
        )
